// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "input": string;
      "ignoreContentTypes": string;
      "s3.provider": string;
      "s3.accessKeyId": string;
      "s3.secretAccessKey": string;
      "s3.region": string;
      "s3.bucketName": string;
      "s3.endpoint": string;
      "r2.customDomain": string;
      "r2.autoSavePublicUrl": boolean;
      "r2.urlType": string;
      "cloudflare.apiToken": string;
      "s3.useCollectionHierarchy": boolean;
    };
  }
}
